"""initial

Revision ID: c0e7c73298b9
Revises: 
Create Date: 2025-05-06 21:15:26.432205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy

# revision identifiers, used by Alembic.
revision: str = 'c0e7c73298b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'crud_users', sa.Column('name', sa.String(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('id',
                  sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
                  nullable=False),
        sa.Column('created_at',
                  advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
                  nullable=False),
        sa.Column('updated_at',
                  advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_crud_users')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crud_users')
    # ### end Alembic commands ###
