"""initial

Revision ID: dcf448cc9bb2
Revises: 
Create Date: 2025-05-06 01:13:27.377079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy

# revision identifiers, used by Alembic.
revision: str = 'dcf448cc9bb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user', sa.Column('name', sa.String(), nullable=False),
        sa.Column('surname', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('id',
                  sa.BigInteger().with_variant(sa.Integer(), 'sqlite'),
                  nullable=False),
        sa.Column('created_at',
                  advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
                  nullable=False),
        sa.Column('updated_at',
                  advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_user')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
